trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: groupname
  type: string
  default: './'

- name: groupdesc
  type: string
  default: 'hi all'
  
- name: envName
  displayName: environment Name
  type: string
  default: primary

- name: variablename
  type: string
  default: 'Devops'

jobs:
  - job: creating_group
    steps:
      - task: PowerShell@2
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        inputs:
          filePath: './setvariables.ps1'
          arguments: 
              -workspace $(Pipeline.Workspace)
              -path ${{parameters.groupname}}
              -bearerToken "$env:SYSTEM_ACCESSTOKEN"
              -organization $(System.CollectionUri)
              -project $(System.TeamProject)
 
  
  - job: templates
    steps:
    - template: ./arm-params-validate.yml
      parameters:
        templates:
        - templateFile: core-resources.json
          resourceGroup: $(coreResourceGroup)
        prefix: core
        outputDirectory: $(Build.StagingDirectory)/templates${{ parameters.envName }}/
 
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'pre-provision-templates${{ parameters.envName }}'
        path: $(Build.StagingDirectory)/templates${{ parameters.envName }}/

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'pre-provision-scripts${{ parameters.envName }}'
        path: $(Build.Repository.LocalPath)/
    
    
