trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: groupname
  type: string
  default: 'newGroup'

- name: groupdesc
  type: string
  default: 'hi all'

- name: variablename
  type: string
  default: 'Devops'

- name: variablevalue
  type: string
  default: 'Joe'

jobs:
  - job: creating_group
    steps:
      - task: PowerShell@2
        inputs:
          filePath: '$(Pipeline.Workspace)/create_variable_group.ps1'
          arguments: '-groupName ${{parameters.groupname}}'